### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by koraybalci** [QuantumConcepts/STLdotNET#14]
If I use your library (binaries from nuget) to save in stl format, am I restricted to use agpl as well or free to choose whichever licensing I like for my application?

Thanks for the lib by the way.

**Comment by JoshMcCullough** [comment]
Yes, that's fine. Any changes/adaptations you make to the STL processing in this library are expected to be shared with the community, that is all. :)

**Comment by Savallator** [comment]
AGPL forces you to make your whole application agpl as well, therefore it makes this lib unusable for most projects. I really don't like to be forced to open-source my whole project for some library. Looks like the author did not understand the implications of AGPL.

**Comment by Trolldemorted** [comment]
Not just your application, but also everything that talks to your application over the network. If keeping changes to STLdotNET public was your intent, could you release it under LGPL?
