### ISSUE TITLE
Wrong separator

### ISSUE THREAD

**Issue by djbios** [QuantumConcepts/STLdotNET#15]
I try to use this library, and i am from Russia. Writing to file not working, because you use default culture separator in numbers, and in Russia it ",". But in STL, separator must be ".". Fix it please.

**Comment by djbios** [comment]
Now see, that this issue already marked, sorry for duplication.

**Comment by JoshMcCullough** [comment]
This is fixed in v1.3.1: https://github.com/QuantumConcepts/STLdotNET/releases/tag/v1.3.1

Sorry for the delay!
